GET http://localhost:3000/api

###

GET http://localhost:3000/api/2

###

POST http://localhost:3000/api
Content-Type: application/json
Accept: application/application/json

 {
        "food": "bread and rice",
        "cost": "5000",
        "id": 1
      }

###

PUT http://localhost:3000/api/2
Content-Type: application/json
Accept: application/json

{
  {
        "food": "food",
        "cost": "1337",
      }
}

### 

DELETE http://localhost:3000/api/6
Accept: application/json